# Generated by Django 5.1.3 on 2024-12-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admNo',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
